type Query {
  "All the cultural sites from data tourisme plateform"
  data: DataTourisme
}

"General information about the differents sites that you can visit"
type DataTourisme {
  "data name"
  name: String!
  "get all the sites"
  sites: [Site]!
  "get an unique site"
  site(id: ID!): Site
}

"General information about a specific site"
type Site {
  "site id"
  id: ID!
  "site name"
  name: String
  "site description"
  description: String
  "site types"
  type: [String]!
  "site language"
  language: [String]
  "site location"
  location: Location
  "site picture representation"
  picture: String
  "site has picture representation"
  hasRepresentation: Boolean
}

"Classic geoLocation format"
type Location {
  latitude: Float
  longitude: Float
}
