type Query {
  "All the cultural sites from data tourisme plateform"
  datas: DataTourisme
}

"General information about the differents sites that you can visit"
type DataTourisme {
  "datas name"
  name: String!
  "sites"
  sites: [Site]!
  "madata"
  madata: String!
}

"General information about a specific site"
type Site {
  "site id"
  id: ID!
  "site name"
  name: String
  "site description"
  description: String
  "site types"
  type: [String]!
}
